# Generated by Django 3.2.8 on 2022-11-08 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тапсырма атауы')),
                ('description', models.CharField(blank=True, max_length=520, null=True, verbose_name='Тапсырма сипаттамасы')),
                ('start_time', models.DateTimeField(verbose_name='Бастау уақыт')),
                ('end_time', models.DateTimeField(verbose_name='Аяқтау уақыт')),
                ('funds', models.PositiveIntegerField(verbose_name='Бөлінген қаржы')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Тапсырма аяқталған')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Құрушы')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Жоба')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Тапсырма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Қатысушы')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Нәтиже сипаттамасы')),
                ('file', models.FileField(null=True, upload_to='task/result/', verbose_name='Қосымша құжат')),
                ('submitted_time', models.DateTimeField(auto_now_add=True, verbose_name='Тапсыған уақыт')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Тапсырушы')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Тапсырма Нәтижесі',
                'verbose_name_plural': 'Тапсырма Нәтижелері',
                'db_table': 'submitted_result',
            },
        ),
    ]
