# Generated by Django 3.2.8 on 2022-05-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Тапсырма атауы')),
                ('description', models.CharField(max_length=255, verbose_name='Тапсырма сипаттамасы')),
                ('start_time', models.DateTimeField(verbose_name='Бастау уақыт')),
                ('end_time', models.DateTimeField(verbose_name='Аяқтау уақыт')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Құрушы')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task/result/')),
                ('submitted', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('finished', models.BooleanField(default=False, verbose_name='Аяқталды')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Тапсырушы')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Тапсырма Нәтижесі',
                'verbose_name_plural': 'Тапсырма Нәтижелері',
                'db_table': 'task_result',
            },
        ),
    ]
