# Generated by Django 3.2.8 on 2024-01-19 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тапсырма атауы')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тапсырма сипаттамасы')),
                ('start_time', models.DateTimeField(verbose_name='Бастау уақыт')),
                ('end_time', models.DateTimeField(verbose_name='Аяқтау уақыт')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], verbose_name='Басымдық')),
                ('tags', models.CharField(max_length=520, verbose_name='Тег')),
                ('finish_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Тапсырма аяқталған уақыт')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыт')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Тапсыпма құрушы')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Жоба')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Тапсырма')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Жауапты мүше')),
            ],
            options={
                'verbose_name': 'Жауапты мүше',
                'verbose_name_plural': 'Жауапты мүшелер',
                'db_table': 'task_workder',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=520, verbose_name='Пікір')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Тапсырма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пайдаланушы')),
            ],
            options={
                'verbose_name': 'Тапсырма пікірі',
                'verbose_name_plural': 'Тапсырма пікірлері',
                'db_table': 'task_comment',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='task/attachement/', verbose_name='Тіркеме')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Тапсырма')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Жүкеуші')),
            ],
            options={
                'verbose_name': 'Тапсырма тіркемесі',
                'verbose_name_plural': 'Тапсырма тіркемелері',
                'db_table': 'task_attachement',
            },
        ),
    ]
