# Generated by Django 3.2.8 on 2022-11-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskprincipal',
            options={'verbose_name': 'Жауапты мүше', 'verbose_name_plural': 'Жауапты мүшелер'},
        ),
        migrations.AlterField(
            model_name='taskprincipal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Жауапты мүше'),
        ),
        migrations.AlterModelTable(
            name='taskprincipal',
            table='task_principal',
        ),
    ]
