# Generated by Django 3.2.8 on 2022-05-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20220517_1558'),
        ('task', '0002_auto_20220517_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Команда'),
            preserve_default=False,
        ),
    ]
