# Generated by Django 3.2.8 on 2024-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20240218_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Backlog'), (1, 'Analyze'), (2, 'Develop'), (3, 'Test'), (4, 'Finish')], default=0, verbose_name='Күй'),
            preserve_default=False,
        ),
    ]
