# Generated by Django 3.2.8 on 2024-04-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='user.user', verbose_name='Жауапты мүше'),
        ),
        migrations.DeleteModel(
            name='TaskWorker',
        ),
    ]
