# Generated by Django 3.2.8 on 2022-05-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=254, null=True, verbose_name='Тапсырма сипаттамасы'),
        ),
    ]
