# Generated by Django 3.2.8 on 2022-05-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='funds',
            field=models.PositiveIntegerField(default=1000, verbose_name='Бөлінген қаржы'),
            preserve_default=False,
        ),
    ]
