# Generated by Django 3.2.8 on 2022-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20220517_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Команда сипаттамасы'),
        ),
    ]
