# Generated by Django 3.2.8 on 2022-05-21 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Қосылған уақыт'),
            preserve_default=False,
        ),
    ]
